"use client";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";

import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto">
          <Navbar />
          {children}
          <ProgressBar
            height="3px"
            color="#fffd00"
            options={{ showSpinner: false }}
          />
          <Footer />
        </div>
      </body>
    </html>
  );
}
